USE [master]
GO

/****** Object:  Database [defter]    Script Date: 01/10/2013 07:44:57 ******/
CREATE DATABASE [defter] ON  PRIMARY 
( NAME = N'defter', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\defter.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'defter_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\defter_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [defter] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [defter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [defter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [defter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [defter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [defter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [defter] SET ARITHABORT OFF 
GO

ALTER DATABASE [defter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [defter] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [defter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [defter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [defter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [defter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [defter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [defter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [defter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [defter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [defter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [defter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [defter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [defter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [defter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [defter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [defter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [defter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [defter] SET  READ_WRITE 
GO

ALTER DATABASE [defter] SET RECOVERY FULL 
GO

ALTER DATABASE [defter] SET  MULTI_USER 
GO

ALTER DATABASE [defter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [defter] SET DB_CHAINING OFF 
GO

